### ISSUE TITLE
接收消息异常

### ISSUE THREAD

**Issue by wyh497823256** [yaphone/itchat4jdemo#1]
![image](https://user-images.githubusercontent.com/8830870/27116717-5b4a9a8a-5105-11e7-9cb7-7297889167bf.png)

**Comment by yaphone** [comment]
朋友你好，这是个示例项目，代码较老，请在这里使用最新代码   https://github.com/yaphone/itchat4j

**Comment by wyh497823256** [comment]
@yaphone  thanks
